variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_FETCH_EXTRA_FLAGS: --tags
  GIT_DEPTH: none

image:
  name: registry.gitlab.com/wanted-project/wanted-engine/build
  entrypoint: [""]

stages:
  - build
  - test


.build_job_template: &build_defs  # Hidden yaml configuration that defines an anchor named 'job_configuration'
  stage: build
  artifacts:
    paths:
    - $BUILD_DIR
    expire_in: 20 minutes
  script:
    - echo -n "Building version:"
    - git describe --tags --abbrev=0
    - mkdir -p "$BUILD_DIR"
    - cd "$BUILD_DIR"
    - cmake -GNinja $CMAKE_EXTRA_ARGS ..
    - ninja

.unit_test_job_template: &unit_defs
  stage: test
  script:
    - cd "$BUILD_DIR"
    - ctest --output-junit rspec.xml
  artifacts:
    when: always
    paths:
      - "$BUILD_DIR/rspec.xml"
    reports:
      junit: "$BUILD_DIR/rspec.xml"


build-gcc:
  <<: *build_defs
  variables:
    BUILD_DIR: build-gcc
    CC: gcc

build-clang:
  <<: *build_defs
  variables:
    BUILD_DIR: build-clang
    CC: clang

build-coverage:
  <<: *build_defs
  variables:
    BUILD_DIR: build
    CC: gcc
    CMAKE_EXTRA_ARGS: -DENABLE_CODE_COVERAGE=on -DCMAKE_BUILD_TYPE=Coverage

unit-test-gcc:
  <<: *unit_defs
  dependencies:
    - build-gcc
  variables:
    BUILD_DIR: build-gcc

unit-test-clang:
  <<: *unit_defs
  dependencies:
    - build-clang
  variables:
    BUILD_DIR: build-clang

coverage:
  stage: test
  dependencies:
    - build-coverage
  variables:
    BUILD_DIR: build
  script:
    - cd "$BUILD_DIR"
    - ninja coverage
  coverage: '/lines: \d+\.\d+/'
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    paths:
      - "$BUILD_DIR/coverage.xml"
    reports:
      coverage_report:
        coverage_format: cobertura
        path: "$BUILD_DIR/coverage.xml"