# WANTED Engine — canonical command runner.
#
# Every build/test/lint recipe lives here and assumes it runs *inside* the
# standardized build container (toolchain on PATH, repo at the working dir).
# That is how CI and the devcontainer invoke them.
#
# Overrides are read from the environment so one recipe serves local + CI:
#   BUILD_DIR (default build) · DEFCONFIG (a name under configs/, sans suffix)
#   CC · CMAKE_EXTRA_ARGS · NUTTX_SKIP_BUILD · NUTTX_CLEAN

build_dir := env_var_or_default("BUILD_DIR", "build")
defconfig := env_var_or_default("DEFCONFIG", "")
cmake_extra := env_var_or_default("CMAKE_EXTRA_ARGS", "")

# Optional board defconfig (configs/<name>_defconfig), used only when this build
# dir has no .config yet — an existing configuration is never overwritten by a
# build. Change one afterwards with `just menuconfig` or `just defconfig <name>`.
defconfig_arg := if defconfig != "" { "-DWANTED_DEFCONFIG=" + defconfig } else { "" }

# OpenWrt SDKs for the cross-architecture lanes. Deliberately *generic* targets
# rather than any specific board: armsr ("ARM SystemReady") and malta (the QEMU
# reference board) are OpenWrt's board-independent targets, so the lane proves
# the architecture rather than one router. Both come from the same release and
# toolchain, so a difference between them is a difference in the architecture.
openwrt_release := "24.10.0"
sdk_base := "https://downloads.openwrt.org/releases/" + openwrt_release + "/targets"
sdk_suffix := "_gcc-13.3.0_musl.Linux-x86_64.tar.zst"
sdk_aarch64 := sdk_base + "/armsr/armv8/openwrt-sdk-" + openwrt_release + "-armsr-armv8" + sdk_suffix
sdk_mipsel := sdk_base + "/malta/le/openwrt-sdk-" + openwrt_release + "-malta-le" + sdk_suffix

# First-party C/H sources (vendored deps and generated trees are excluded).
src_dirs := "src platform cmd include"
# clang-tidy reads flags per TU from this build's compile_commands.json.
tidy_build_dir := env_var_or_default("TIDY_BUILD_DIR", "build-clang")

# List available recipes.
default:
    @just --list

# Build the engine + CLI and run the unit suite.
all: build test

# --- build ----------------------------------------------------------------
# No dependency on the wasm recipes: the supervisor TAR is loaded by path at
# runtime, so it only has to exist (built separately via `make wasm`) by boot.

# --- configuration --------------------------------------------------------
# The engine's build configuration is a Kconfig tree (tools/kconfiglib). Each
# build dir owns its own .config, so {{build_dir}} selects which one these act
# on. The generated header lands at {{build_dir}}/include/wanted-autoconf.h and
# is regenerated by the next cmake run, which `build` performs.

kconfig := "PYTHONPATH=" + justfile_directory() + "/tools/kconfiglib KCONFIG_CONFIG=" + build_dir + "/.config"
kcl := justfile_directory() + "/tools/kconfiglib"

# Edit this build dir's configuration in the terminal UI.
# On a bare host run it through `make menuconfig`, which allocates a TTY.
menuconfig:
    mkdir -p {{build_dir}}
    {{kconfig}} python3 {{kcl}}/menuconfig.py Kconfig

# Write the minimal defconfig for this build dir's .config to configs/<name>.
savedefconfig name:
    {{kconfig}} python3 {{kcl}}/savedefconfig.py --kconfig Kconfig --out configs/{{name}}

# Seed this build dir's .config from configs/<name>, replacing any existing one.
defconfig name:
    mkdir -p {{build_dir}}
    {{kconfig}} python3 {{kcl}}/defconfig.py --kconfig Kconfig configs/{{name}}

# Bring this build dir's .config forward over Kconfig edits (new symbols take
# their default instead of silently reading as n).
olddefconfig:
    {{kconfig}} python3 {{kcl}}/olddefconfig.py Kconfig

# Select the supervisor image for this build dir (sheriff | wsh | selftest)
# without disturbing the rest of its configuration.
supervisor-variant name:
    mkdir -p {{build_dir}}
    {{kconfig}} python3 {{kcl}}/setconfig.py --kconfig Kconfig \
        WANTED_SUPERVISOR_$(echo {{name}} | tr a-z A-Z)=y

# Build the engine + CLI with the production (sheriff) supervisor [DEFCONFIG=...].
build:
    mkdir -p {{build_dir}}
    cd {{build_dir}} && cmake -GNinja {{defconfig_arg}} {{cmake_extra}} .. && ninja

# Build the engine + CLI with the wsh debug supervisor selected [DEFCONFIG=...].
wsh:
    mkdir -p {{build_dir}}
    cd {{build_dir}} && cmake -GNinja {{defconfig_arg}} {{cmake_extra}} .. >/dev/null
    just supervisor-variant wsh
    cd {{build_dir}} && cmake -GNinja {{cmake_extra}} .. && ninja

# Build a production OpenWrt .ipk -> dist/. sdk = SDK URL or local SDK dir.
# Point it at whichever target the deployment runs; the two shorthands below
# build for the generic per-architecture targets.
openwrt-package sdk:
    packaging/openwrt/openwrt-package.sh "{{sdk}}"

# .ipk for generic 64-bit ARM / 32-bit little-endian MIPS.
openwrt-package-aarch64:
    packaging/openwrt/openwrt-package.sh "{{sdk_aarch64}}"

openwrt-package-mipsel:
    packaging/openwrt/openwrt-package.sh "{{sdk_mipsel}}"

# --- test (run against an already-built {{build_dir}}) ---------------------

# Run the unit + smoke suite via ctest (JUnit report emitted for CI).
test:
    cd {{build_dir}} && ctest -j"$(nproc)" --output-on-failure --output-junit rspec.xml

# Build and test with an out-of-tree driver tree linked in, asserting extra
# drivers resolve and that one claiming a core name still loses to core.
test-extra-drivers:
    mkdir -p build-extra-drivers
    cd build-extra-drivers && cmake -GNinja {{defconfig_arg}} {{cmake_extra}} \
        -DWANTED_EXTRA_DRIVERS_DIR={{justfile_directory()}}/test/extra-drivers .. && ninja
    cd build-extra-drivers && ctest -j"$(nproc)" --output-on-failure -R driver_tables

# Cobertura coverage report (build with CMAKE_EXTRA_ARGS=-DENABLE_CODE_COVERAGE=on).
coverage:
    cd {{build_dir}} && ninja coverage

# Boot the production supervisor and assert a clean instantiate.
smoke-engine:
    ./test/smoke-engine.sh ./{{build_dir}}/cmd/wanted-cli

# Run the in-WASM selftest suite on Linux.
selftest:
    ./test/selftest.sh ./{{build_dir}}/cmd/wanted-cli

# Run the in-WASM selftest suite against a cross-built engine under qemu.
# sdk = OpenWrt SDK URL or local SDK dir; the two shorthands below pin the
# generic per-architecture SDKs. The SDK is cached under .openwrt-sdk/.
selftest-qemu sdk:
    ./test/selftest-qemu.sh "{{sdk}}"

# 64-bit ARM (armsr/armv8) — generic, not a specific board.
selftest-qemu-aarch64:
    ./test/selftest-qemu.sh "{{sdk_aarch64}}"

# 32-bit little-endian MIPS (malta/le) — generic, not a specific board.
selftest-qemu-mipsel:
    ./test/selftest-qemu.sh "{{sdk_mipsel}}"

# Run the system-control (poweroff/reboot/exit) checks on Linux.
syscontrol:
    ./test/syscontrol.sh ./{{build_dir}}/cmd/wanted-cli

# Swap the supervisor image under a running engine: child wapps keep running,
# an armed reload adopts the staged image, a bad one rolls back.
live-update:
    BUILD_DIR=build-wsh just wsh
    ./test/live-update.sh ./build-wsh/cmd/wanted-cli

# Negative test: WASM_MAX_MEMORY_PAGES bounds a wapp's linear-memory growth.
memcap:
    ./test/memcap.sh

# Package the ESP-IDF factory-seed images from built wapps. The firmware embeds
# these into the app binary, so they must exist before `idf.py build`; they are
# gitignored artifacts, like every other packaged .wapp. Needs `just wapps`
# (wapp SDK image) to have produced the .wasm files first.
registry-seed:
    #!/usr/bin/env bash
    set -euo pipefail
    mkdir -p wasm/registry-seed
    for n in looper wifi-connect devcheck; do
        src="wapps/$n/$n.wasm"
        [ -f "$src" ] || { echo "registry-seed: $src missing — run 'make wapps' first" >&2; exit 1; }
        s=$(mktemp -d); cp "$src" "$s/app.wasm"
        tar --format=ustar --owner=0 --group=0 --mtime='1970-01-01 00:00:00 UTC' \
            -C "$s" -cf "wasm/registry-seed/$n.wapp" app.wasm
        rm -rf "$s"
        echo "registry-seed: wasm/registry-seed/$n.wapp"
    done

# Report per-wapp + engine memory footprint per profile (linux + nuttx ABIs).
sizes:
    ./utils/measure-sizes.sh

# --- NuttX simulator ------------------------------------------------------
# The build/test recipe lives in test/nuttx-sim.sh (shared with CI); these
# recipes just dispatch to it. DEFCONFIG / NUTTX_SKIP_BUILD / NUTTX_CLEAN are read
# from the environment by the script.

# Link the engine app package into the checked-out nuttx-apps submodule.
nuttx-deps:
    ./test/nuttx-sim.sh deps

# Configure + build the NuttX sim (wsh as init over hostfs) [DEFCONFIG=...].
nuttx-build:
    ./test/nuttx-sim.sh deps build

# Build just the sim kernel binary (no hostfs staging) — the split-CI artifact.
nuttx-kernel:
    ./test/nuttx-sim.sh kernel

# Run the in-WASM selftest suite on the NuttX sim.
nuttx-selftest:
    ./test/nuttx-sim.sh selftest

# Run the system-control (poweroff/reboot/exit) checks on the NuttX sim.
nuttx-syscontrol:
    ./test/nuttx-sim.sh syscontrol

# Distclean the NuttX submodule tree.
nuttx-clean:
    ./test/nuttx-sim.sh clean

# --- ESP32 firmware (real hardware) ---------------------------------------
# Cross-build the NuttX firmware for the Waveshare ESP32 One. Run *inside the
# xtensa toolchain image*; the Makefile `esp32` target stages the supervisor +
# nuttx-deps in the build image first, then runs this in the xtensa image.
# Output is third_party/nuttx/nuttx.bin, flashed at 0x1000 (ESP32 Simple Boot).
esp32-build:
    cd third_party/nuttx && \
        { [ -f .config ] || ./tools/configure.sh -a ../nuttx-apps esp32-devkitc:wanted; } && \
        make -j"$(nproc)" WANTED_DEFCONFIG=esp32-nuttx_defconfig

# --- clean ----------------------------------------------------------------

# Remove every build artifact (Linux + NuttX sim + wasm/wapps + submodule objects).
clean:
    rm -rf {{build_dir}} build-nuttx registry
    # Every supervisor app.wasm is a gitignored build output, sheriff's included.
    rm -f wasm/*.wasm* wasm/supervisor/*/supervisor.tar wasm/supervisor/*/app.wasm
    rm -f wapps/*/*.wasm wapps/*/*.wasm.h wapps/*/*.o
    # NuttX kernel objects + .config live in the submodule tree; an incremental
    # rebuild over a stale tree silently runs old code, so distclean it too.
    ./test/nuttx-sim.sh clean

# --- lint / static analysis / security ------------------------------------

# All blocking lint checks.
lint: lint-format lint-shell

# Reject any formatting drift (clang-format config in .clang-format). Prunes
# ESP-IDF's own build/vendored dirs under platform/esp-idf/project/ (build/,
# managed_components/, .cache/ — gitignored, not our source; idf.py downloads
# and regenerates them, so linting them is both wrong and non-reproducible).
lint-format:
    find {{src_dirs}} \( -name build -o -name 'build.*' -o -name managed_components -o -name .cache \) -prune -o \( -name '*.c' -o -name '*.h' \) -print0 \
        | xargs -0 clang-format --dry-run --Werror

# Reformat the tree in place (developer helper; not run in CI).
format-fix:
    find {{src_dirs}} \( -name build -o -name 'build.*' -o -name managed_components -o -name .cache \) -prune -o \( -name '*.c' -o -name '*.h' \) -print0 \
        | xargs -0 clang-format -i

# Lint shell scripts. error severity only for now; ratchet down over time.
lint-shell:
    find . -name '*.sh' -not -path './vendor/*' -not -path './third_party/*' -not -path './build*/*' -not -path './.openwrt-sdk/*' -print0 \
        | xargs -0 shellcheck --severity=error

# Configure + build the clang build dir clang-tidy reads compile_commands.json
# from. Idempotent: a no-op when the dir is already built (CI build-clang
# artifact). Builds so generated headers (e.g. the supervisor config) exist.
tidy-build:
    mkdir -p {{tidy_build_dir}}
    cd {{tidy_build_dir}} && CC=clang cmake -GNinja .. && ninja

# clang-tidy the compiled first-party sources. The file list is taken from the
# compile DB so conditionally-built sources (e.g. ssocket.c without OpenSSL) are
# analysed only when actually compiled. --config-file pins the root config so
# clang-tidy never loads a vendored .clang-tidy from an included header's tree.
tidy: tidy-build
    clang-tidy -p {{tidy_build_dir}} --config-file=.clang-tidy --warnings-as-errors='*' \
        $(python3 -c "import json,os; print('\n'.join(sorted({os.path.relpath(e['file']) for e in json.load(open('{{tidy_build_dir}}/compile_commands.json')) if os.path.relpath(e['file']).startswith(('src/','platform/linux/','cmd/'))})))")

# cppcheck does its own parsing, so it covers every platform without a build.
# Excludes ESP-IDF's own downloaded/generated build/managed_components/.cache
# dirs (idf.py-owned, not our source — same reasoning as lint-format's prune).
cppcheck:
    #!/bin/sh
    set -e
    excludes=""
    for d in $(find platform/esp-idf -type d \( -name build -o -name managed_components -o -name .cache \) 2>/dev/null); do
        excludes="$excludes -i$d"
    done
    # cppcheck parses without a build, so it has no generated configuration
    # header. Without one every CONFIG_WANTED_* reads as undefined: the host
    # guard's #error fires, and the configurable drivers analyse as absent.
    # Generate one from the Kconfig defaults (every driver on) into a scratch
    # dir so the analysis sees the code as it is actually built.
    cfg=$(mktemp -d); trap 'rm -rf "$cfg"' EXIT
    PYTHONPATH=tools/kconfiglib KCONFIG_CONFIG="$cfg/.config" \
        python3 tools/kconfiglib/olddefconfig.py Kconfig >/dev/null
    PYTHONPATH=tools/kconfiglib KCONFIG_CONFIG="$cfg/.config" \
        python3 tools/kconfiglib/genconfig.py --header-path "$cfg/wanted-autoconf.h" \
        Kconfig >/dev/null
    cppcheck --enable=warning,style,performance,portability \
        --suppress=missingIncludeSystem --suppress=normalCheckLevelMaxBranches \
        --inline-suppr --error-exitcode=1 \
        -I include -I src/include -I platform/include -I "$cfg" \
        -DCONFIG_RP23XX_FLASH_MTD_MOUNTPOINT='"/mnt/flash"' \
        $excludes \
        src platform cmd

# gcc -fanalyzer: deep but slow/verbose — run out-of-band, not on every push.
analyze build_dir="build-analyze":
    mkdir -p {{build_dir}}
    cd {{build_dir}} && cmake -GNinja -DCMAKE_C_FLAGS="-fanalyzer" .. && ninja

# Pattern-based security scan (C/C++ ruleset).
security:
    semgrep --config "p/c" --error --quiet {{src_dirs}}

# Scan the build image definition and the working tree for CVEs and secrets.
scan-image:
    trivy config --severity HIGH,CRITICAL docker/Dockerfile
    trivy fs --severity HIGH,CRITICAL --scanners vuln,secret .
