/* SPDX-License-Identifier: Apache-2.0 */

/* RP2350 init shim. The supervisor OCI TAR is bundled as a ROMFS image at /rom;
 * board bring-up mounts the registry's LittleFS volume, so this shim chdirs
 * into it, seeds factory wapps and owns the console. */

#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <poll.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include <sys/boardctl.h>
#include <sys/mount.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>

#include <nuttx/usb/cdcacm.h>

#include <config-nuttx.h>
#include <platform.h>
#include <wanted.h>
#include <wanted_log.h>

#include "boot-romfs.h" /* generated: boot_romfs_img[], boot_romfs_img_len */
#include "debug_trace.h"

#define ROMFS_MINOR 0
#define ROMFS_SECTSIZE 512
#define ROMFS_DEVPATH "/dev/ram" /* + minor */
#define ROMFS_MOUNTPT "/rom"

#define CDCACM_DEVMINOR 0
#define CDCACM_DEVPATH "/dev/ttyACM0"

/* Writable persistent registry storage: the LittleFS volume board bring-up
 * already mounted over the internal-flash MTD region at
 * CONFIG_RP23XX_FLASH_MTD_MOUNTPOINT. */
#define REGISTRY_VOLUME CONFIG_RP23XX_FLASH_MTD_MOUNTPOINT

int wanted_main(int argc, char *argv[]);

#define SEED_DIR                                                               \
    ROMFS_MOUNTPT "/registry" /* /rom/registry (bundled factory wapps) */
#define REGISTRY_DIR REGISTRY_ROOT
#define SEED_COPY_BUF 1024

/* Copy one factory image from the read-only boot ROMFS into the writable
 * registry. Best-effort: a failure just means that image is not installed. */
static void seed_copy(const char *src, const char *dst) {
    int in = open(src, O_RDONLY);
    if (in < 0)
        return;
    int out = open(dst, O_WRONLY | O_CREAT | O_EXCL, 0644);
    if (out < 0) {
        close(in);
        return;
    }
    char buf[SEED_COPY_BUF];
    ssize_t n;
    while ((n = read(in, buf, sizeof(buf))) > 0) {
        if (write(out, buf, (size_t)n) != n)
            break;
    }
    close(in);
    close(out);
}

/* First-boot factory seed: copy any /rom/registry/*.wapp the firmware bundles
 * into the writable registry, skipping those already installed. A freshly
 * flashed board can then start its bundled wapps with no network. */
static void seed_registry(void) {
    DIR *d = opendir(SEED_DIR);
    if (!d) {
        DEBUG_TRACE("opendir(%s) failed: %s", SEED_DIR, strerror(errno));
        return; /* no factory bundle */
    }
    mkdir(REGISTRY_DIR, 0755);
    const struct dirent *e;
    while ((e = readdir(d)) != NULL) {
        if (e->d_name[0] == '.')
            continue;
        DEBUG_TRACE("seeding %s", e->d_name);
        char src[256], dst[256];
        snprintf(src, sizeof(src), "%s/%s", SEED_DIR, e->d_name);
        snprintf(dst, sizeof(dst), "%s/%s", REGISTRY_DIR, e->d_name);
        seed_copy(src, dst);
    }
    closedir(d);
}

#ifdef CONFIG_SYSTEM_WANTED_PROVISION_PROMPT

/* Supervisor state, relative to the registry volume this shim chdirs into. */
#define STATE_DIR "sheriff"
#define PROVISION_PATH STATE_DIR "/provision"
#define SECRET_PATH STATE_DIR "/secret"
#define PROVISION_MAX 1024
#define PROVISION_WAIT_MS 30000

/* Ask the console for a base64 provisioning blob and store it verbatim
 * Returns with nothing written when the operator does
 * not answer */
static void prompt_provision(void) {
    struct stat st;
    if (stat(SECRET_PATH, &st) == 0)
        return;

    if (mkdir(STATE_DIR, 0755) < 0 && errno != EEXIST) {
        perror("mkdir " STATE_DIR);
        return;
    }

    printf("\nno device identity. paste a provisioning blob and press Enter,\n"
           "or wait %d s to start unprovisioned.\n> ",
           PROVISION_WAIT_MS / 1000);
    fflush(stdout);

    struct pollfd pfd = {.fd = STDIN_FILENO, .events = POLLIN};
    if (poll(&pfd, 1, PROVISION_WAIT_MS) <= 0) {
        printf("\nno blob entered.\n");
        return;
    }

    char blob[PROVISION_MAX];
    size_t len = 0;
    while (len < sizeof(blob) - 1) {
        char c;
        ssize_t n = read(STDIN_FILENO, &c, 1);
        if (n <= 0 || c == '\r' || c == '\n')
            break;
        blob[len++] = c;
    }
    if (len == 0) {
        printf("\nno blob entered.\n");
        return;
    }

    int fd = open(PROVISION_PATH, O_WRONLY | O_CREAT | O_TRUNC, 0644);
    if (fd < 0) {
        perror(PROVISION_PATH);
        return;
    }
    if (write(fd, blob, len) != (ssize_t)len)
        perror(PROVISION_PATH);
    close(fd);
    printf("\nstored %lu B at %s\n", (unsigned long)len, PROVISION_PATH);
}

#endif /* CONFIG_SYSTEM_WANTED_PROVISION_PROMPT */

/* Launch config as bytes — no filesystem holds one at first boot. Generated by
 * test/nuttx-sim.sh from the configured JSON. */
#include "wanted-config.h"

/* Connects the CDCACM class driver so CDCACM_DEVPATH exists and is openable,
 * for the console transport or for a wapp's `serial://` socket. NuttX has
 * no "already connected" query, so this is only ever called once. */
static void connect_usb_cdcacm(void) {
    struct boardioc_usbdev_ctrl_s ctrl = {
        .usbdev = BOARDIOC_USBDEV_CDCACM,
        .action = BOARDIOC_USBDEV_CONNECT,
        .instance = CDCACM_DEVMINOR,
        .handle = NULL,
    };
    FAR void *handle;
    ctrl.handle = &handle;

    if (boardctl(BOARDIOC_USBDEV_CONTROL, (uintptr_t)&ctrl) < 0) {
        perror("boardctl(USBDEV_CDCACM)");
    }
}

#ifndef CONFIG_UART0_SERIAL_CONSOLE
/* Bring up the USB-CDC console: connect the CDCACM class driver, then block
 * until a host terminal opens the port and sends a few carriage returns before
 * binding fd 0-2, or early engine output races the terminal attaching. */
/* How long to wait for a host terminal before giving up and booting anyway.
 * Long enough to plug in and press a key, short enough that a board nobody is
 * watching still reaches the engine. */
#define USB_CONSOLE_WAIT_S 30

/* Adopts the USB CDC as the console only once a terminal sends three
 * newlines. A CDC write nobody reads blocks, so an unattended port would
 * hang the engine's first printf; times out rather than waiting forever. */
static void bring_up_usb_console(void) {
    connect_usb_cdcacm();

    const time_t deadline = time(NULL) + USB_CONSOLE_WAIT_S;
    int fd = -1;

    while (fd < 0 && time(NULL) < deadline) {
        fd = open(CDCACM_DEVPATH, O_RDWR);
        if (fd < 0)
            sleep(1);
    }
    if (fd < 0) {
        DEBUG_TRACE("usb console: %s never appeared; booting without it",
                    CDCACM_DEVPATH);
        return;
    }

    int nlc = 0;
    while (nlc < 3 && time(NULL) < deadline) {
        struct pollfd pfd = {.fd = fd, .events = POLLIN};
        char inch = 0;

        if (poll(&pfd, 1, 500) <= 0)
            continue;
        if (read(fd, &inch, 1) != 1)
            break; /* host went away */
        nlc = (inch == '\n' || inch == '\r') ? nlc + 1 : 0;
    }

    if (nlc < 3) {
        /* Not adopted: writing to a port nobody reads would block the boot. */
        close(fd);
        DEBUG_TRACE("usb console: no terminal within %d s; booting without it",
                    USB_CONSOLE_WAIT_S);
        return;
    }

    dup2(fd, 0);
    dup2(fd, 1);
    dup2(fd, 2);
    if (fd > 2)
        close(fd);
}
#endif /* !CONFIG_UART0_SERIAL_CONSOLE */

/* Records a slot that failed to confirm after a repeat boot attempt, to
 * the engine's error channel — the one account of a bad update that
 * survives the reboot that hid it. */
static void report_boot_slot(void) {
    if (PlatformOtaInit() != 0) {
        DEBUG_TRACE("ota: boot state unavailable");
        return;
    }

    platform_ota_state_t st;
    if (PlatformOtaGetBootState(&st) != 0)
        return;

    DEBUG_TRACE("ota: booted slot %c (%s), attempt %d", st.active_slot,
                st.confirmed ? "confirmed" : "unconfirmed", st.boot_attempts);

    if (!st.confirmed && st.boot_attempts > 1)
        LOG_ERROR("ota: slot %c did not confirm after %d attempts; "
                  "the loader reverted",
                  st.active_slot, st.boot_attempts);
}

int wanted_rp2350_main(int argc, char *argv[]) {
    /* Must run before anything else (littlefs/ROMFS mount, seed_registry
     * file I/O) touches the shared heap and fragments its one big PSRAM
     * free node - see PlatformExtramEarlyInit's doc comment. */
    PlatformExtramEarlyInit();

    struct boardioc_romdisk_s desc = {
        .minor = ROMFS_MINOR,
        .nsectors = (boot_romfs_img_len + ROMFS_SECTSIZE - 1) / ROMFS_SECTSIZE,
        .sectsize = ROMFS_SECTSIZE,
        .image = (FAR uint8_t *)boot_romfs_img,
    };

    if (boardctl(BOARDIOC_ROMDISK, (uintptr_t)&desc) < 0) {
        perror("boardctl(ROMDISK)");
    } else if (mount(ROMFS_DEVPATH "0", ROMFS_MOUNTPT, "romfs", MS_RDONLY,
                     NULL) < 0) {
        perror("mount " ROMFS_MOUNTPT);
    }

#ifdef CONFIG_UART0_SERIAL_CONSOLE
    /* UART0 already owns fd 0-2; still connect CDC-ACM for a wapp's
     * `serial://` socket. */
    connect_usb_cdcacm();
#else
    bring_up_usb_console();
#endif

    /* Done after the console is up so failures here are visible. */
    bool startConfigured = false;
    if (chdir(REGISTRY_VOLUME) < 0) {
        perror("chdir " REGISTRY_VOLUME);
    } else {
        DEBUG_TRACE("chdir %s ok", REGISTRY_VOLUME);
        seed_registry();
#ifdef CONFIG_SYSTEM_WANTED_PROVISION_PROMPT
        startConfigured = true;
        prompt_provision();
#endif
    }

    /* Before the engine starts, so a slot that failed is recorded even if the
     * supervisor never comes up. */
    report_boot_slot();

    int rc;
    if (startConfigured) {
        rc = WantedStart(wantedDefaultConfig, strlen(wantedDefaultConfig));
    } else {
        rc = wanted_main(argc, argv);
    }

    /* Engine loop returned (supervisor drained / poweroff requested). Power the
     * board off so we don't idle in init; falls through if the config lacks
     * BOARDCTL_POWEROFF. */
    boardctl(BOARDIOC_POWEROFF, rc);
    return rc;
}
